version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fantasy-writer-db
    environment:
      POSTGRES_DB: fantasy_writer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fantasy_writer_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasy_writer_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fantasy_writer_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: your-256-bit-secret-key-here-make-it-long-and-secure
    networks:
      - fantasy_writer_network

volumes:
  postgres_data:

networks:
  fantasy_writer_network:
    driver: bridge 