services:
  mongo-db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - '27017:27017'

    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fantasy
    volumes:
      - mongodata:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo-db

    depends_on:
      - mongo-db
    networks:
      - mongo-network


volumes:
  mongodata:

networks:
  mongo-network:
    driver: bridge