global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'text-to-image-service'
    static_configs:
      - targets: ['text-to-image:5002']
    metrics_path: '/metrics'

  - job_name: 'text-to-speech-service'
    static_configs:
      - targets: ['text-to-speech:5001']
    metrics_path: '/metrics'

  - job_name: 'summary-service'
    static_configs:
      - targets: ['summary-service:5003']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5004']
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9090']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics' 